# file: roles/cherokee/tasks/main.yml
---

  - name: add cherokee ppa
    sudo: yes
    apt_repository: repo="ppa:cherokee-webserver" state="present"
    register: ppa_add
    ignore_errors: true
    
  - name: package install
    sudo: yes
    apt: pkg="{{ item }}" state="present" update_cache="yes"
    with_items:
      - cherokee
      - libcherokee-mod-libssl
    register: apt_install
    ignore_errors: true
    when: ppa_add|success
    
  - apt: pkg="{{ item }}" state="present"
    sudo: yes
    with_items:
      - make
      - libtool
      - automake
      - unzip
      - gettext
    when: apt_install|failure

  - name: install from source code (fallback)
    copy: src=../files/webserver-1.2.103.d021376.zip dest=/tmp mode=0644
    when: apt_install|failure
    
  - command: chdir=/tmp tar xvzf /tmp/webserver-1.2.103.d021376.zip
    when: apt_install|failure

  - command: chdir=/tmp/webserver-1.2.103.d021376.zip {{ item }}
    sudo: yes
    with_items:
      - ./autogen.sh --prefix=/usr --localstatedir=/var --sysconfdir=/etc
      - make
      - make install
    when: apt_install|failure

  
