# file: roles/cherokee/tasks/main.yml
---

  # - name: add cherokee ppa
  #   sudo: yes
  #   apt_repository: repo="ppa:cherokee-webserver" state="present"
  #   register: ppa_add
  #   ignore_errors: true

  # - name: package install
  #   sudo: yes
  #   apt: "pkg={{ item }} state=present update_cache=yes"
  #   with_items:
  #     - cherokee
  #     - libcherokee-mod-libssl
  #   register: apt_install
  #   ignore_errors: true
  #   when: ppa_add|success

  # - name: remove cherokee ppas
  #   sudo: yes
  #   apt_repository: "repo=ppa:cherokee-webserver state=absent"
  #   when: ppa_add|failed

  - name: check for cherokee
    command: which cherokee
    register: cherokee_exists
    ignore_errors: true

  - name: install cherokee prerequisites
    apt: "pkg={{ item }} state=present"
    sudo: yes
    with_items:
      - make
      - libtool
      - automake
      - unzip
      - gettext
    when: cherokee_exists|failed
    # when: ppa_add|failed or apt_install|failed

  - name: install from source
    copy: src=../files/webserver-1.2.103.d021376.zip dest=/tmp mode=0644
    # when: ppa_add|failed or apt_install|failed
    when: cherokee_exists|failed

  - name: expand source
    command: chdir=/tmp unzip -o /tmp/webserver-1.2.103.d021376.zip
    # when: ppa_add|failed or apt_install|failed
    when: cherokee_exists|failed

  - name: compile source
    command: chdir=/tmp/webserver-1.2.103.d021376 {{ item }}
    sudo: yes
    with_items:
      - ./autogen.sh --prefix=/usr --localstatedir=/var --sysconfdir=/etc
      - make
      - make install
      - 
    # when: ppa_add|failed or apt_install|failed
    when: cherokee_exists|failed


  - name: add service file
    command: chdir=/tmp/webserver-1.2.103.d021376/contrib {{ item }}
    sudo: yes
    with_items:
      - make
      - cp cherokee /etc/init.d/cherokee
    # when: cherokee_exists|failed
